// Generated by CoffeeScript 1.6.2
var app;

app = app || {};

$(function() {
  app.widgets = new app.Widgets();
  app.deskView = new app.DeskView({
    collection: app.widgets
  });
  return app.widgets.reset(app.data);
});
