// Generated by CoffeeScript 1.6.2
var note, notes;

note = new Note({
  "text": "Nur ein Test"
});

note.save({
  text: "bla bla"
}, {
  wait: true
}, {
  success: function() {
    return console.log(note.toJSON());
  }
});

note.save("pos", {
  x: 200,
  y: 100
}, {
  success: function() {
    return console.log(note.toJSON());
  }
});

notes = new Notes;
