// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var note;

    note = new Note({
      "text": "Nur ein Test"
    });
    return console.log(note.toJSON());
  });

}).call(this);
