// Generated by CoffeeScript 1.6.2
var Note, Notes, _ref, _ref1,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Note = (function(_super) {
  __extends(Note, _super);

  function Note() {
    _ref = Note.__super__.constructor.apply(this, arguments);
    return _ref;
  }

  Note.prototype.urlRoot = 'server.php/notes';

  Note.prototype.defaults = {
    text: "",
    pos: {
      x: 0,
      y: 0
    },
    size: {
      width: 100,
      height: 100
    }
  };

  Note.prototype.initialize = function() {
    return this.on("all", function(e) {
      return console.log("Note event:" + e + ' text:' + this.get("text"));
    });
  };

  Note.prototype.validate = function(attrs, options) {};

  return Note;

})(Backbone.Model);

Notes = (function(_super) {
  __extends(Notes, _super);

  function Notes() {
    _ref1 = Notes.__super__.constructor.apply(this, arguments);
    return _ref1;
  }

  Notes.prototype.url = 'server.php/notes';

  Notes.prototype.model = Note;

  return Notes;

})(Backbone.Collection);
