// Generated by CoffeeScript 1.6.2
var app,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

app = app || {};

$(function() {
  var delay, _ref, _ref1, _ref2, _ref3;

  app.Note = (function(_super) {
    __extends(Note, _super);

    function Note() {
      _ref = Note.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Note.prototype.urlRoot = 'server.php/notes';

    Note.prototype.defaults = {
      text: "",
      pos: {
        x: 0,
        y: 0
      },
      size: {
        width: 100,
        height: 100
      }
    };

    Note.prototype.initialize = function() {
      this.on("change:pos", this.savePos);
      this.on("change:text", this.saveText);
      return this.on("all", function(e) {
        return console.log("Note event:" + e);
      });
    };

    Note.prototype.savePos = function() {
      return this.save(this.pos);
    };

    Note.prototype.saveText = function() {
      return this.save(this.text);
    };

    Note.prototype.validate = function(attrs, options) {};

    return Note;

  })(Backbone.Model);
  app.Notes = (function(_super) {
    __extends(Notes, _super);

    function Notes() {
      _ref1 = Notes.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    Notes.prototype.url = 'server.php/notes';

    Notes.prototype.model = app.Note;

    return Notes;

  })(Backbone.Collection);
  app.NoteView = (function(_super) {
    __extends(NoteView, _super);

    function NoteView() {
      _ref2 = NoteView.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    NoteView.prototype.template = _.template($('#item-template').html());

    NoteView.prototype.className = "notes ui-widget-content";

    NoteView.prototype.isDragging = false;

    NoteView.prototype.events = {
      "click .close": "clear",
      "mouseup": "enableEdit",
      "focusout": "editDone"
    };

    NoteView.prototype.initialize = function() {
      this.listenTo(this.model, 'destroy', this.remove);
      this.listenTo(this.model, 'change:id', this.render);
      return this.render();
    };

    NoteView.prototype.render = function() {
      this.$el.html(this.template(this.model.toJSON()));
      return this.$el.offset(this.model.get("pos"));
    };

    NoteView.prototype.enableEdit = function() {
      if (!this.isDragging) {
        $('.marked', this.el).hide();
        return $('textarea', this.el).show();
      }
    };

    NoteView.prototype.editDone = function() {
      this.model.set("text", $('textarea', this.el).val());
      return this.showMarked();
    };

    NoteView.prototype.showMarked = function() {
      var marked_v, text_v;

      text_v = $('textarea', this.el).val();
      marked_v = marked(text_v);
      $('.marked', this.el).html(marked_v);
      $('textarea', this.el).hide();
      return $('.marked', this.el).show();
    };

    NoteView.prototype.startDrag = function() {
      return this.isDragging = true;
    };

    NoteView.prototype.stopDrag = function(position) {
      var _this = this;

      delay(100, function() {
        return _this.isDragging = false;
      });
      return this.model.set("pos", position);
    };

    NoteView.prototype.clear = function(e) {
      e.stopImmediatePropagation();
      return this.model.destroy();
    };

    return NoteView;

  })(Backbone.View);
  app.DeskView = (function(_super) {
    __extends(DeskView, _super);

    function DeskView() {
      _ref3 = DeskView.__super__.constructor.apply(this, arguments);
      return _ref3;
    }

    DeskView.prototype.initialize = function() {
      this.listenTo(app.notes, 'add', this.addOne);
      return marked.setOptions({
        breaks: true
      });
    };

    DeskView.prototype.el = '#wrapper';

    DeskView.prototype.events = {
      "click #add": "addNote",
      "add": "addOne"
    };

    DeskView.prototype.addNote = function() {
      return app.notes.create();
    };

    DeskView.prototype.addOne = function(note) {
      var noteView;

      noteView = new app.NoteView({
        model: note,
        id: "note-" + note.cid
      });
      $('#wrapper').append(noteView.el);
      noteView.$el.draggable({
        stack: ".notes",
        delay: 100,
        start: function(event, ui) {
          return noteView.startDrag();
        },
        stop: function(event, ui) {
          return noteView.stopDrag(ui.position);
        }
      });
      return noteView.showMarked();
    };

    return DeskView;

  })(Backbone.View);
  return delay = function(ms, func) {
    return setTimeout(func, ms);
  };
});
