// Generated by CoffeeScript 1.6.2
var app,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

app = app || {};

$(function() {
  var delay, _ref, _ref1, _ref2;

  app.WidgetView = (function(_super) {
    __extends(WidgetView, _super);

    function WidgetView() {
      _ref = WidgetView.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    WidgetView.prototype.template = _.template($('#item-template').html());

    WidgetView.prototype.className = "notes ui-widget-content";

    WidgetView.prototype.isDragging = false;

    WidgetView.prototype.isResizing = false;

    WidgetView.prototype.events = {
      "mousedown .close": "clear",
      "mouseup .close": "stopClear"
    };

    WidgetView.prototype.initialize = function() {
      this.listenTo(this.model, 'destroy', this.remove);
      return this.render();
    };

    WidgetView.prototype.render = function() {
      var _this = this;

      this.$el.html(this.template(this.model.toJSON()));
      this.$el.offset(this.model.get("pos"));
      this.$el.width(this.model.get("size").width);
      this.$el.height(this.model.get("size").height);
      $('#desk').append(this.el);
      this.$el.draggable({
        stack: ".notes",
        delay: 100,
        start: function(event, ui) {
          return _this.startDrag();
        },
        stop: function(event, ui) {
          return _this.stopDrag(ui.position);
        }
      });
      this.$el.resizable({
        start: function(event, ui) {
          return _this.startResize();
        },
        stop: function(event, ui) {
          return _this.stopResize(ui.size);
        }
      });
      return this.$el;
    };

    WidgetView.prototype.startDrag = function() {
      return this.isDragging = true;
    };

    WidgetView.prototype.stopDrag = function(position) {
      var _this = this;

      delay(100, function() {
        return _this.isDragging = false;
      });
      this.model.set("z-index", this.$el.css('z-index'));
      return this.model.set("pos", position);
    };

    WidgetView.prototype.startResize = function() {
      return this.isResizing = true;
    };

    WidgetView.prototype.stopResize = function(size) {
      var _this = this;

      delay(100, function() {
        return _this.isResizing = false;
      });
      return this.model.set("size", size);
    };

    WidgetView.prototype.clear = function(e) {
      var _this = this;

      return this.$el.fadeOut(1000, function() {
        return _this.model.destroy();
      });
    };

    WidgetView.prototype.stopClear = function(e) {
      return this.$el.stop().css("opacity", "1");
    };

    return WidgetView;

  })(Backbone.View);
  app.WidgetFactory = (function() {
    function WidgetFactory() {}

    WidgetFactory.prototype.buildView = function(params) {
      switch (params.type) {
        case "note":
          return new app.NoteView(params);
      }
    };

    return WidgetFactory;

  })();
  app.NoteView = (function(_super) {
    __extends(NoteView, _super);

    function NoteView() {
      _ref1 = NoteView.__super__.constructor.apply(this, arguments);
      return _ref1;
    }

    NoteView.prototype.initialize = function() {
      NoteView.__super__.initialize.call(this);
      return marked.setOptions({
        breaks: true
      });
    };

    NoteView.prototype.events = function() {
      return _.extend({}, app.WidgetView.prototype.events, {
        "click .marked": "enableEdit",
        "focusout": "editDone"
      });
    };

    NoteView.prototype.render = function() {
      NoteView.__super__.render.call(this);
      return this.showMarked();
    };

    NoteView.prototype.enableEdit = function(e) {
      if (!this.isDragging && !this.isResizing && !this.collection.isLocked) {
        e.preventDefault();
        if (this.collection.editEl !== null) {
          this.collection.editEl.editDone();
        }
        $('.marked', this.el).hide();
        $('textarea', this.el).show().focus();
        this.oldText = $('textarea', this.el).val();
        return this.collection.editEl = this;
      }
    };

    NoteView.prototype.editDone = function() {
      var text;

      text = $('textarea', this.el).val();
      if (text !== this.oldText) {
        this.model.set("text", text);
      }
      this.showMarked();
      return this.collection.editEl = null;
    };

    NoteView.prototype.showMarked = function() {
      var $m, marked_v, text_v;

      $m = $('.marked', this.el);
      text_v = $('textarea', this.el).val();
      marked_v = marked(text_v);
      $m.html(marked_v);
      $('textarea', this.el).hide();
      return $m.show();
    };

    return NoteView;

  })(app.WidgetView);
  app.DeskView = (function(_super) {
    __extends(DeskView, _super);

    function DeskView() {
      _ref2 = DeskView.__super__.constructor.apply(this, arguments);
      return _ref2;
    }

    DeskView.prototype.initialize = function() {
      this.listenTo(this.collection, 'add', this.addOne);
      this.listenTo(this.collection, 'reset', this.addAll);
      return this.widgetFactory = new app.WidgetFactory();
    };

    DeskView.prototype.el = '#wrapper';

    DeskView.prototype.events = {
      "click #add": "create",
      "add": "addOne",
      "click #toggleEdit": "toggleEdit"
    };

    DeskView.prototype.create = function() {
      var l, z;

      z = 1;
      l = this.collection.last();
      if (l !== void 0) {
        z = l.get("z-index") + 1;
      }
      return this.collection.create({
        type: "note",
        "z-index": z
      });
    };

    DeskView.prototype.addOne = function(widget) {
      var type, widgetView;

      type = "note";
      return widgetView = this.widgetFactory.buildView({
        type: type,
        collection: this.collection,
        model: widget,
        id: "note-" + widget.cid
      });
    };

    DeskView.prototype.addAll = function(collection) {
      return _.each(collection.models, this.addOne, this);
    };

    DeskView.prototype.toggleEdit = function() {
      if (this.collection.isLocked) {
        this.collection.isLocked = false;
        return $("#toggleEdit span").removeClass("ui-icon-locked").addClass("ui-icon-unlocked");
      } else {
        this.collection.isLocked = true;
        return $("#toggleEdit span").removeClass("ui-icon-unlocked").addClass("ui-icon-locked");
      }
    };

    return DeskView;

  })(Backbone.View);
  delay = function(ms, func) {
    return setTimeout(func, ms);
  };
});
